# Generated by Django 3.2.9 on 2022-07-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlshortenermodel',
            options={'verbose_name': 'Сокращенный путь', 'verbose_name_plural': 'Сокращенные пути'},
        ),
        migrations.AlterField(
            model_name='urlshortenermodel',
            name='new_url',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='urlshortenermodel',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
